services:
  # --- NGINX (The Gateway) ---
  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # only expose port 80 for HTTP traffic
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    restart: always
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # ports:
    #   - "5000:5000"
    volumes:
      - ./data/datasets:/data/datasets
      - privatized_datasets:/data/privatized_datasets
      - ./modules:/modules
      - ./benchmarks:/benchmarks
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://user:password@db:5432/dbname
      - JWT_SECRET_KEY=jwtsecretkey
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      # CRITICAL FOR PRODUCTION: Do not wipe the DB on restart
      - CLEAN_DB=true
      - POSTGRES_PASSWORD=password
    # GPU CONFIGURATION
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    # Restart automatically if it crashes or the VM reboots
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    entrypoint: ["/app/entrypoint.sh"]

  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    hostname: worker1
    volumes:
      - ./data/datasets:/data/datasets
      - privatized_datasets:/data/privatized_datasets
      - ./modules:/modules
      - ./benchmarks:/benchmarks
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/dbname
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - C_FORCE_ROOT=true
    # GPU CONFIGURATION
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    restart: always
    depends_on:
      - redis
      - backend
    entrypoint: ["/app/celery_entrypoint.sh"]
    tty: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # Pass the variable during the BUILD process
      args:
        REACT_APP_API_URL: http://privbench.test/api
    # ports:
      # - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://privbench.local/api
    restart: always

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d dbname"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data
    restart: always

volumes:
  postgres_data:
  redis_data:
  privatized_datasets: