version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://user:password@db:5432/dbname
      - JWT_SECRET_KEY=REDACTED_JWT_KEY
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./data/datasets:/data/datasets
      - privatized_datasets:/data/privatized_datasets
      - ./modules:/modules
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    entrypoint: ["/app/entrypoint.sh"]

  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    hostname: worker1
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/dbname
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - C_FORCE_ROOT=true
    volumes:
      - ./data/datasets:/data/datasets
      - privatized_datasets:/data/privatized_datasets
      - ./modules:/modules
    depends_on:
      - redis
      - backend
    entrypoint: ["/app/celery_entrypoint.sh"]
    tty: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000 

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d dbname"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
  privatized_datasets: