//fixme: delete this
export const RankingData = [
    { rank: 1, name: "Aurora Shield", method: "Encryption", submittedBy: "DataWizard123", badges: ["Gold", "Verified"], score: 100 },
    { rank: 2, name: "Nebula Cloak", method: "Anonymization", submittedBy: "CyberNinja77", badges: ["Silver"], score: 98 },
    { rank: 3, name: "Titan Vault", method: "Tokenization", submittedBy: "SecureCoder", badges: ["Bronze"], score: 96 },
    { rank: 4, name: "Phantom Lock", method: "Pseudonymization", submittedBy: "DataSage", badges: ["Gold", "Verified"], score: 94 },
    { rank: 5, name: "Crystal Guardian", method: "Encryption", submittedBy: "ShieldBear99", badges: ["Silver", "Verified"], score: 92 },
    { rank: 6, name: "Obsidian Fog", method: "Anonymization", submittedBy: "FogMaster", badges: ["Bronze"], score: 90 },
    { rank: 7, name: "Cipher Veil", method: "Pseudonymization", submittedBy: "CodePhantom", badges: ["Gold"], score: 88 },
    { rank: 8, name: "Iron Cipher", method: "Tokenization", submittedBy: "SecureTiger", badges: ["Verified"], score: 86 },
    { rank: 9, name: "Velvet Lockbox", method: "Encryption", submittedBy: "DigitalKnight", badges: ["Gold", "Silver"], score: 84 },
    { rank: 10, name: "Starlight Seal", method: "Anonymization", submittedBy: "DataCrusader", badges: ["Bronze", "Verified"], score: 82 },
    { rank: 11, name: "Shadow Keep", method: "Tokenization", submittedBy: "SilentHawk", badges: ["Silver"], score: 80 },
    { rank: 12, name: "Quantum Ward", method: "Pseudonymization", submittedBy: "EclipseUser", badges: ["Gold", "Verified"], score: 78 },
    { rank: 13, name: "Emerald Barrier", method: "Encryption", submittedBy: "GuardianGreen", badges: ["Gold"], score: 76 },
    { rank: 14, name: "Onyx Firewall", method: "Anonymization", submittedBy: "DarkUser", badges: ["Bronze", "Verified"], score: 74 },
    { rank: 15, name: "Lunar Vault", method: "Tokenization", submittedBy: "CyberWolf", badges: ["Silver"], score: 72 },
    { rank: 16, name: "Solar Cloak", method: "Pseudonymization", submittedBy: "LightBringer", badges: ["Gold", "Verified"], score: 70 },
    { rank: 17, name: "Sapphire Shield", method: "Encryption", submittedBy: "OceanicCoder", badges: ["Bronze"], score: 68 },
    { rank: 18, name: "Digital Mirage", method: "Anonymization", submittedBy: "MirageUser", badges: ["Gold", "Silver"], score: 66 },
    { rank: 19, name: "Void Shroud", method: "Tokenization", submittedBy: "NullMaster", badges: ["Verified"], score: 64 },
    { rank: 20, name: "Infinity Wall", method: "Pseudonymization", submittedBy: "InfiniteMind", badges: ["Gold", "Bronze"], score: 62 },
    { rank: 21, name: "Amber Fort", method: "Encryption", submittedBy: "AmberUser", badges: ["Silver"], score: 60 },
    { rank: 22, name: "Nebula Sphere", method: "Anonymization", submittedBy: "StarScribe", badges: ["Bronze", "Verified"], score: 58 },
    { rank: 23, name: "Eclipse Seal", method: "Tokenization", submittedBy: "ShadowRanger", badges: ["Verified"], score: 56 },
    { rank: 24, name: "Ivory Aegis", method: "Pseudonymization", submittedBy: "PaleGuardian", badges: ["Gold"], score: 54 },
    { rank: 25, name: "Vortex Barrier", method: "Encryption", submittedBy: "StormRider", badges: ["Silver"], score: 52 },
    { rank: 26, name: "Crimson Cloak", method: "Anonymization", submittedBy: "RedPhantom", badges: ["Bronze"], score: 50 },
    { rank: 27, name: "Azure Wall", method: "Tokenization", submittedBy: "BlueKnight", badges: ["Verified"], score: 48 },
    { rank: 28, name: "Oblivion Sphere", method: "Pseudonymization", submittedBy: "VoidUser", badges: ["Silver"], score: 46 },
    { rank: 29, name: "Shadowed Ward", method: "Encryption", submittedBy: "DarkSentinel", badges: ["Bronze", "Verified"], score: 44 },
    { rank: 30, name: "Cobalt Bastion", method: "Anonymization", submittedBy: "SteelGuardian", badges: ["Gold"], score: 42 },
];
