#!/bin/bash
set -e
FLASK_PID=""

# Trap SIGINT and SIGTERM to stop containers gracefully
cleanup() {
    echo "Stopping module containers..."
    python -m flask stop-containers || echo "Failed to stop containers"

    echo "Stopping Flask server..."
    if [ -n "$FLASK_PID" ]; then
        kill "$FLASK_PID"
        wait "$FLASK_PID" 2>/dev/null
    fi

    echo "Cleanup complete. Exiting."
    exit 0
}
trap cleanup SIGINT SIGTERM

# Function to wait for Redis
wait_for_redis() {
    echo "Waiting for Redis..."
    sleep 2
    while ! nc -z redis 6379; do
        sleep 1
    done
    echo "Redis is up!"
    redis-cli -h redis ping
}

# Function to wait for PostgreSQL
wait_for_postgres() {
    echo "Waiting for PostgreSQL..."
    while ! nc -z db 5432; do
        sleep 1
    done
    echo "PostgreSQL is ready!"
}

wait_for_flask() {
    echo "Waiting for Flask to be ready..."
    until curl -s http://localhost:5000/health > /dev/null; do
        sleep 1
    done
    echo "Flask is up!"
}

# Function to run database setup and population scripts
run_db_scripts() {
    # Ensure the database is ready before running the scripts
    echo "Waiting for the database to be ready..."
    until pg_isready -h db -p 5432 -U "$POSTGRES_USER"; do
      sleep 1
    done

    echo "Database is ready."

    # Run the database setup script to add modules
    echo "Running setup-db.py..."
    python /app/setup-db.py

    # Populate the database  //FIXME: remove this in production, only needed for demo data
    if [ "$FLASK_ENV" = "development" ]; then
        echo "Running populate-db.py..."
        python /app/populate-db.py
    fi
    
}

# Function to handle database migrations
setup_database() {
    # 1. Handle Clean Reset
    if [ "$FLASK_ENV" = "development" ] && [ "$CLEAN_DB" = "true" ]; then
        echo "Resetting DB and migrations..."
        PGPASSWORD=$POSTGRES_PASSWORD psql -h db -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "DROP SCHEMA public CASCADE; CREATE SCHEMA public;"
        rm -rf migrations
    fi

    # 2. Init if missing
    if [ ! -d "migrations" ]; then
        echo "Initializing migrations..."
        python -m flask db init
    fi

    # 3. Always attempt an upgrade first
    echo "Applying existing migrations..."
    python -m flask db upgrade || echo "Upgrade failed, checking for new changes..."

    # 4. Attempt to migrate only if needed, without killing the script on "no changes"
    echo "Checking for model changes..."
    python -m flask db migrate -m "Autogenerated migration" || echo "No new changes to migrate."
    
    # 5. Final upgrade to catch any newly generated migration
    python -m flask db upgrade || echo "Migration failed, but starting anyway..."
    
    # 6. Run population scripts
    if [ "$CLEAN_DB" = "true" ]; then
        run_db_scripts
    fi
}

# Main execution logic for Flask backend
echo "Starting Flask backend..."
wait_for_redis
wait_for_postgres

set +e
setup_database
set -e

echo "Starting the Flask application..."
#python -m flask run --host=0.0.0.0 &
"$@" &
FLASK_PID=$!

# Wait for Flask to be ready
wait_for_flask

# Start module containers
echo "Starting module containers..."
chmod 666 /var/run/docker.sock || echo "Warning: Could not set socket permissions"
python -m flask start-containers

# Bring Flask process back to foreground
wait $FLASK_PID