#!/bin/bash
set -e
FLASK_PID=""

# Activate virtual environment from root directory
if [ -d "../venv" ]; then
    source ../venv/bin/activate
else
    echo "Virtual environment not found in root directory"
    exit 1
fi

# Load environment variables from .env, ignoring comments and empty lines
if [ -f .env ]; then
    echo "Loading .env file..."
    export $(grep -v '^#' .env | grep -v '^$' | xargs)
else
    echo "Warning: .env file not found"
fi


# Trap SIGINT and SIGTERM to stop containers gracefully
cleanup() {
    echo "Stopping module containers..."
    python -m flask stop-containers || echo "Failed to stop containers"

    echo "Stopping Flask server..."
    if [ -n "$FLASK_PID" ]; then
        kill "$FLASK_PID"
        wait "$FLASK_PID" 2>/dev/null
    fi

    echo "Cleanup complete. Exiting."
    exit 0
}
trap cleanup SIGINT SIGTERM

# Function to wait for Redis
wait_for_redis() {
    echo "Waiting for Redis..."
    until redis-cli ping; do
        sleep 1
    done
    echo "Redis is up!"
}

# Function to wait for PostgreSQL
wait_for_postgres() {
    echo "Waiting for PostgreSQL..."
    while ! nc -z localhost 5432; do
        sleep 1
    done
    echo "PostgreSQL is ready!"
}

wait_for_flask() {
    echo "Waiting for Flask to be ready..."
    until curl -s http://localhost:5000/health > /dev/null; do
        sleep 1
    done
    echo "Flask is up!"
}

# Function to run database setup and population scripts
run_db_scripts() {
    # Ensure the database is ready before running the scripts
    echo "Waiting for the database to be ready..."
    until pg_isready -h localhost -p 5432 -U user; do
      sleep 1
    done

    echo "Database is ready."

    # Run the database setup script to add modules
    echo "Running setup-db.py..."
    python setup-db.py

    # Populate the database  //FIXME: remove this in production, only needed for demo data
    if [ "$FLASK_ENV" = "development" ]; then
        echo "Running populate-db.py..."
        python populate-db.py
    fi
    
}

# Function to handle database migrations
setup_database() {
    echo "DEBUG: FLASK_ENV is: '$FLASK_ENV'"
    echo "DEBUG: CLEAN_DB is: '$CLEAN_DB'"
    if [ "$FLASK_ENV" = "development" ] && [ "$CLEAN_DB" = "true" ]; then
        echo "Resetting DB and migrations..."
        PGPASSWORD=$POSTGRES_PASSWORD psql -h localhost -U user -d dbname -c "DROP SCHEMA public CASCADE; CREATE SCHEMA public;"
        rm -rf migrations
    fi

    if [ ! -d "migrations" ]; then
        echo "Initializing migrations..."
        python -m flask db init
        echo "Migrations initialized successfully"
    else
        echo "Migrations directory already exists"
    fi

    # Verify versions directory exists (should be created by flask db init)
    if [ ! -d "migrations/versions" ]; then
        echo "Warning: migrations/versions directory missing. Creating it..."
        mkdir -p migrations/versions
    fi

    echo "Generating migrations..."
    if python -m flask db migrate -m "Autogenerated migration"; then
        echo "New migrations created. Applying them..."
        python -m flask db upgrade
    else
        echo "No model changes detected. Skipping upgrade."
    fi
    # Run database setup and population scripts only if CLEAN_DB is true
    if [ "$CLEAN_DB" = "true" ]; then
        run_db_scripts
    fi
    
}

# Main execution logic for Flask backend
echo "Starting Flask backend..."
wait_for_redis
wait_for_postgres
setup_database

echo "Starting the Flask application..."
# python -m flask run --host=0.0.0.0 &
python -m debugpy --listen 5678 -m flask run --host=0.0.0.0 --no-reload --no-debugger &
FLASK_PID=$!

# Wait for Flask to be ready
wait_for_flask

# Start module containers
echo "Starting module containers..."
python -m flask start-containers

# Bring Flask process back to foreground
wait $FLASK_PID